package com.cheesecake.presentation.screens.favoritecompetitionsselection

sealed interface FavoriteCompetitionSelectionNavigationEvent {
    object NavigateToFavoriteTeamsSelection: FavoriteCompetitionSelectionNavigationEvent
}